### ISSUE TITLE
Roadmap for ABbiodiversity organization

### ISSUE THREAD

**Issue by psolymos** [ABbiodiversity/abbiodiversity.github.io#1]
Ideas for possible repositories to add:

- [ ] Accessing raw species data from Oracle/API (exists but not public)
- [ ] Geospatial data summaries (exists as bunch of script files)
- [ ] Analysis + results summary scripts by taxa (exists as bunch of script files)
- [x] cure4insect: presenting results
- [x] Dev website (kind of done)

**Comment by mabecker89** [comment]
Git - Tutorial, files to practice with, list of help resources.

**Comment by mabecker89** [comment]
Any thoughts @beallen?

**Comment by beallen** [comment]
I think that is a good list to start with as they represent the core products of the SC. 

As a tutorial/blog post idea, I think it would be good to have an example of scenario modeling using the cure4insect package. Do something similar to the Indian Farm Creek project and show how changing cropland to pasture or native grassland affects biodiversity.

**Comment by psolymos** [comment]
It is on my list actually, but I lack a realistic public data set that has
ideally a grid intersected with land cover polys.

**Comment by psolymos** [comment]
@beallen @mabecker89 here is an idea for the git workshop for the fall: I have started the species modeling manual. Once I make it a proper repository for our manuals, that can be a real case study for collaboration (creating branches, making PRs etc). And, we get stuff done as a result.
